repo: openworm/hodgkin_huxley_tutorial
shortDescription: "Hodgkin Huxley Tutorial"
coordinator: stephen@openworm.org
earnable-badges: 
  - "http://www.badgelist.com/OpenWorm/Hodgkin-Huxley-Tutorial-Graduate"
keywords: 
  - tutorial
  - simulation
  - conductance-based models
languages: 
  - markdown
members: 
  - joe.b.bowen@gmail.com 
  - p.gleeson@gmail.com
parent: 
  - openworm/OpenWorm
